In [1]:
from numpy import *
import numpy.matlib as matlib
import itertools
import sys

In [2]:
DEBUG = True

GRID_HEIGHT = 4
GRID_WIDTH = 4

class Action:
    value_map = {'up':0, 'down':1, 'left':2, 'right':3}
    
    def __init__(self, value):
        self.value = value.lower()
        self.index = self.value_map[self.value]
        
    def __eq__(self, other):
        if self.index == other.index:
            return True
        return False
    
    def __str__(self):
        return self.value
    
    
class State:
    def __init__(self, i, j):
        self.i = i
        self.j = j
        self.index = self.i * GRID_HEIGHT + self.j
   
    def left_of(self, other):
        if self.i == other.i and self.j - other.j == -1:
            return True
        return False

    def right_of(self, other):
        if self.i == other.i and self.j - other.j == 1:
            return True
        return False

    def above(self, other):
        if self.j == other.j and self.i - other.i == -1:
            return True
        return False

    def below(self, other):
        if self.j == other.j and self.i - other.i == 1:
            return True
        return False
    
    def on_top_edge(self):
        if self.i == 0:
            return True
        
    def on_bottom_edge(self):
        if self.i == GRID_HEIGHT - 1:
            return True
        
    def on_left_edge(self):
        if self.j == 0:
            return True
        
    def on_right_edge(self):
        if self.j == GRID_WIDTH - 1:
            return True
        
    def __eq__(self, other):
        if self.index == other.index:
            return True
        return False
    
    def __str__(self):
        return 's{}{}'.format(self.i,self.j)
    
actions = [Action('up'), Action('down'), Action('left'), Action('right')]
states = [State(i,j) for i,j in itertools.product(range(GRID_HEIGHT), range(GRID_WIDTH))]

# terminal states
s_term = [State(0,0), State(3,3)]

In [3]:
# |S| x |A|
uni_random_policy = full(shape=(len(states), len(actions)), fill_value=0.25)

In [4]:
def trans(s, a, s_p):
    if s in s_term:
        return 0.0
    if a == Action('up'):
        if s_p.above(s) or (s == s_p and s.on_top_edge()):
            return 1.0
    elif a == Action('down'):
        if s_p.below(s) or (s == s_p and s.on_bottom_edge()):
            return 1.0
    elif a == Action('left'):
        if s_p.left_of(s) or (s == s_p and s.on_left_edge()):
            return 1.0
    elif a == Action('right'):
        if s_p.right_of(s) or (s == s_p and s.on_right_edge()):
            return 1.0

    return 0.0
    
# |S| x |A| x |S|
p_trans = zeros(shape=(len(states), len(actions), len(states)))

for s, a, s_p in itertools.product(states, actions, states):
    p_trans[s.index, a.index, s_p.index] = trans(s, a, s_p) 

In [5]:
s = State(3,2)
    
for a in actions:
    for s_p in states:
        p = p_trans[s.index, a.index, s_p.index]
        if p:
            print 'p_trans[{},{},{}] = {}'.format(s,a,s_p,p_trans[s.index, a.index, s_p.index])

p_trans[s32,up,s22] = 1.0
p_trans[s32,down,s32] = 1.0
p_trans[s32,left,s31] = 1.0
p_trans[s32,right,s33] = 1.0


In [6]:
r_term = 0.0  # Reward of terminal state
r_step = -1.0 # Reward for any non-terminal state

gamma = 1.0  # Discount factor

In [7]:
def reward(state, action, next_state):
    if state in s_term:
        return r_term
    else:
        return r_step

# |S| x |A| x |S|
r = zeros(shape=(len(states),len(actions),len(states)))

for s, state in enumerate(states):
    for a, action in enumerate(actions):
        for s_p, next_state in enumerate(states):
            r[s,a,s_p] = reward(state,action,next_state)

In [8]:
def policy_evaluation(policy, vk):
    vk_new = zeros(shape=(len(states)))
    for s, state in enumerate(states):
        for a, action in enumerate(actions):
            for s_p, next_state in enumerate(states):
                vk_new[s] += policy[s, a] * p_trans[s, a, s_p] * (r[s, a, s_p] + gamma * vk[s_p])
    return vk_new

Evaluating Uniform Random Policy

In [9]:
vk = zeros(shape=(len(states)))

NUM_ITERS = 100
for k in range(NUM_ITERS):
    vk = policy_evaluation(uni_random_policy, vk)

vk_uni = copy(vk)
for s in states:
    print '{} = {}'.format(s, vk_uni[s.index])

s00 = 0.0
s01 = -13.9426050861
s02 = -19.914951073
s03 = -21.904825221
s10 = -13.9426050861
s11 = -17.925076925
s12 = -19.9155199931
s13 = -19.914951073
s20 = -19.914951073
s21 = -19.9155199931
s22 = -17.925076925
s23 = -13.9426050861
s30 = -21.904825221
s31 = -19.914951073
s32 = -13.9426050861
s33 = 0.0


In [10]:
def policy_improvement(vk):
    
    new_policy = zeros(shape=(len(states), len(actions)))
    for s, state in enumerate(states):
        max_a = None
        max_vk = -sys.maxint - 1
        for a, action in enumerate(actions):
            vk_cand = 0.0
            for s_p, next_state in enumerate(states):
                vk_cand += p_trans[s, a, s_p] * (r[s, a, s_p] + gamma * vk[s_p])  
            
            if vk_cand > max_vk:
                max_vk = vk_cand
                max_a = a
            
        new_policy[s, max_a] = 1.0
        
    return new_policy

Determine the optimal policy from the state value function for uniform random policy.

In [11]:
optimal_policy = policy_improvement(vk_uni)

In [12]:
optimal_policy

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.]])

Evaluating State Value Function For Optimal Policy

In [13]:
vk_star = zeros(shape=(len(states)))

NUM_ITERS = 100
for k in range(NUM_ITERS):
    vk_star = policy_evaluation(optimal_policy, vk_star)
        
for s in states:
    print '{} = {}'.format(s, vk_star[s.index])

s00 = 0.0
s01 = -1.0
s02 = -2.0
s03 = -3.0
s10 = -1.0
s11 = -2.0
s12 = -3.0
s13 = -2.0
s20 = -2.0
s21 = -3.0
s22 = -2.0
s23 = -1.0
s30 = -3.0
s31 = -2.0
s32 = -1.0
s33 = 0.0


In [14]:
def policy_iteration(policy, vk, k_iters=1, epsilon=1e-4):

    stable_policy = False
    while not stable_policy:
        for k in range(k_iters):
            vk = policy_evaluation(policy, vk)
       
        new_policy = policy_improvement(vk)

        stable_policy = True
        for s in states:
            for a in actions:
                if abs(policy[s.index, a.index] - new_policy[s.index, a.index]) > epsilon:
                    stable_policy = False
                    
        policy = copy(new_policy)
            
    return policy, vk

In [15]:
vk = zeros(shape=(len(states)))
policy_star, vk_star = policy_iteration(uni_random_policy, vk, k_iters=1)

In [16]:
vk_star

array([ 0., -1., -2., -3., -1., -2., -3., -2., -2., -3., -2., -1., -3.,
       -2., -1.,  0.])

In [17]:
policy_star

array([[ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 0.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 1.,  0.,  0.,  0.]])